# Generated by Django 3.1.2 on 2020-11-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
