# Generated by Django 3.1.2 on 2020-11-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0009_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heaer_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
